- name: Configure IPv4 firewall for 4242 & 8042 port
  blockinfile:
    path: /etc/iptables/rules.v4
    block: |
          -A INPUT -p tcp -m state --state NEW -m tcp --dport 4242 -j ACCEPT -m comment --comment "Orthanc DICOM"
          -A INPUT -p tcp -m state --state NEW -m tcp --dport 8042 -j ACCEPT -m comment --comment "Orthanc HTTP"
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited'

- name: Configure IPv6 firewall for 4242 & 8042 port
  blockinfile:
    path: /etc/iptables/rules.v6
    block: |
          -A INPUT -p tcp -m state --state NEW -m tcp --dport 4242 -j ACCEPT -m comment --comment "Orthanc DICOM"
          -A INPUT -p tcp -m state --state NEW -m tcp --dport 8042 -j ACCEPT -m comment --comment "Orthanc HTTP"
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp6-adm-prohibited'