version: '3.1' 
services:
  orthanc:
    image: jodogne/orthanc-plugins:1.12.7
    command: /run/secrets/  
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
      - credentials.json
    environment:
      - ORTHANC_NAME="Orthanc Server"
secrets:
  orthanc.json:
    file: orthanc.json
  credentials.json:
    file: credentials.json