# Create directory for Orthanc data
- name: Create Orthanc data directory
  file:
    path: /opt/orthanc
    state: directory
    owner: root
    group: root
    mode: '0755'

# Copy configuration files
- name: Copy orthanc.json file
  copy:
    src: "orthanc.json"
    dest: /opt/orthanc/orthanc.json

- name: Copy credentials.json file
  copy:
    src: credentials.json
    dest: /opt/orthanc/credentials.json

# Create docker-compose.yml
- name: Create docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/orthanc/docker-compose.yml
    mode: '0644'

- name: Start application with docker-compose
  command: docker compose up -d
  args:
    chdir: /opt/orthanc

- name: Wait for docker to come alive
  wait_for:
    host: "{{ ansible_host }}"
    port: 8042
    timeout: 120
    state: started
    sleep: 10
    delay: 5

- name: Confirm that 200 OK response is returned
  uri:
    url: "http://{{ ansible_host }}:8042"
    status_code: 200
    url_username: "orthanc"
    url_password: "hallelujah"
    force_basic_auth: yes